subinclude("///third_party/github/pleasings//docker")

docker_image(
    name = "prom_multiplexer",
    srcs = [
        "//cmd:metrics-multiplexer-sidecar",
    ],
    image = "prom_multiplexer",
    visibility = ["PUBLIC"],
)
