subinclude("///third_party/github/pleasings//go:mock")

go_mock(
    name = "mocks",
    interfaces = [
        "Cache",
    ],
    package = "github.com/thought-machine/prometheus-multiplexer-sidecar/internal/pkg/cache",
    src_lib = "//internal/pkg/cache",
    visibility = ["PUBLIC"],
)
